name: Release

on:
  push:
    tags:
      - 'v*.*.*'
    inputs:
      create_release:
        description: 'Create Release'
        required: false
        default: 'true'
  # Allows to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      create_release:
        description: 'Create Release'
        required: false
        default: 'draft'

jobs:
  build-artifacts:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.version.outputs.version }}
      version_num: ${{ steps.version.outputs.version_num }}
      archive_filename: ${{ steps.create-archive.outputs.file_name }}
      deb_filename: ${{ steps.build-deb.outputs.file_name }}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: version
        run: |
          ver=${VERSION_REF##*/}
          if [[ "$ver" =~ ^v([0-9]+).([0-9]+).([0-9]+) ]]; then
            echo "::set-output name=version::$ver"
            echo "::set-output name=version_num::${ver:1}"
          else
            echo "::set-output name=version::v0.0.0"
            echo "::set-output name=version_num::0.0.0"
          fi
        env:
          VERSION_REF: ${{ github.ref }}
        shell: bash
        id: version
        
      - name: Prepare dist
        run: |
          mkdir -p dist/usr/local/loveboxpi
          mkdir -p dist/etc/loveboxpi
          cp -r deb/* dist/
          cp -r src/* dist/usr/local/loveboxpi/
          cp -r waveshare_epd/RaspberryPi_JetsonNano/python/lib/waveshare_epd dist/usr/local/loveboxpi/
          echo -n $VERSION_REF > dist/usr/local/loveboxpi/VERSION
        env:
          VERSION_REF: ${{ steps.version.outputs.version_num }}
        shell: bash
        
      - name: Create archive
        run: |
          tar czf $ARCHIVE_NAME -C dist .
          echo "::set-output name=file_name::$ARCHIVE_NAME"
        env:
          ARCHIVE_NAME: loveboxpi_${{ steps.version.outputs.version_num }}.tar.gz
        id: create-archive
      - name: Upload archive artifact
        uses: actions/upload-artifact@v3
        with:
          name: artifact-archive
          path: ${{ steps.create-archive.outputs.file_name }}
        
      - name: Build deb package
        uses: jiro4989/build-deb-action@v2
        with:
          package: loveboxpi
          package_root: dist
          maintainer: raven-worx
          version: ${{ steps.version.outputs.version_num }}
          arch: 'armhf'
          depends: 'python3,python3-rpi.gpio,python3-gpiozero,python3-spidev,python3-numpy,python3-pil,python3-colormap'
          desc: 'LoveboxPi'
        id: build-deb
      - name: Upload deb artifact
        uses: actions/upload-artifact@v3
        with:
          name: artifact-deb
          path: ${{ steps.build-deb.outputs.file_name }}
  
  create-release:
    runs-on: ubuntu-latest
    needs:
      - build-artifacts
    if: ${{ needs.build-artifacts.outputs.version != 'v0.0.0' || (github.event.inputs && contains('true draft', github.event.inputs.create_release)) }}
    steps:
      - uses: actions/checkout@v3
      
      - name: Generate Changelog
        id: changelog
        uses: metcalfc/changelog-generator@v4.0.1
        with:
          myToken: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Create Release
        id: create-release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{needs.build-artifacts.outputs.version}}
          body: |
            ${{ steps.changelog.outputs.changelog }}
            
            ## Install/Update
            
            ```console
            wget -O /tmp/loveboxpi.deb https://github.com/raven-worx/loveboxpi/releases/download/${{needs.build-artifacts.outputs.version}}/loveboxpi_${{needs.build-artifacts.outputs.version_num}}_armhf.deb
            sudo apt update
            sudo apt install /tmp/loveboxpi.deb
            ```
          draft: ${{ github.event.inputs && github.event.inputs.create_release == 'draft' }}
          prerelease: false

      - name: Download archive artifact
        uses: actions/download-artifact@v3
        with:
          name: artifact-archive
          path: dist
      - name: Download deb artifact
        uses: actions/download-artifact@v3
        with:
          name: artifact-deb
          path: dist
        
      - name: Upload archive artifact
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create-release.outputs.upload_url }}
          asset_path: dist/${{ needs.build-artifacts.outputs.archive_filename }}
          asset_name: ${{ needs.build-artifacts.outputs.archive_filename }}
          asset_content_type: application/gzip
        
      - name: Upload deb artifact
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create-release.outputs.upload_url }}
          asset_path: dist/${{ needs.build-artifacts.outputs.deb_filename }}
          asset_name: ${{ needs.build-artifacts.outputs.deb_filename }}
          asset_content_type: application/vnd.debian.binary-package
